INSERT INTO teams(id, loc,              nickname) VALUES
                 (1,  'Arizona',        'Diamondbacks'),
                 (2,  'Atlanta',        'Braves'),
                 (3,  'Baltimore',      'Orioles'),
                 (4,  'Boston',         'Red Sox'),
                 (5,  'Chicago',        'Cubs'),
                 (6,  'Chicago',        'White Sox'),
                 (7,  'Cincinnati',     'Reds'),
                 (8,  'Cleveland',      'Indians'),
                 (9,  'Colorado',       'Rockies'),
                 (10, 'Detroit',        'Tigers'),
                 (11, 'Houston',        'Astros'),
                 (12, 'Kansas City',    'Royals'),
                 (13, 'Los Angeles',    'Angels'),
                 (14, 'Los Angeles',    'Dodgers'),
                 (15, 'Miami',          'Marlins'),
                 (16, 'Milwaukee',      'Brewers'),
                 (17, 'Minnesota',      'Twins'),
                 (18, 'New York',       'Mets'),
                 (19, 'New York',       'Yankees'),
                 (20, 'Oakland',        'Athletics'),
                 (21, 'Philadelphia',   'Phillies'),
                 (22, 'Pittsburgh',     'Pirates'),
                 (23, 'San Diego',      'Padres'),
                 (24, 'San Francisco',  'Giants'),
                 (25, 'Seattle',        'Mariners'),
                 (26, 'St. Louis',      'Cardinals'),
                 (27, 'Tampa Bay',      'Rays'),
                 (28, 'Texas',          'Rangers'),
                 (29, 'Toronto',        'Blue Jays'),
                 (30, 'Washington',     'Nationals');